export const DECK_TAGS_LIST = [
  "All Themes",
  "+1/+1 Counters",
  "-1/-1 Counters",
  "Abzan (WBG)",
  "Affinity",
  "Aggression (WBRG)",
  "Aggro",
  "Aikido",
  "Altruism (WURG)",
  "Aristocrats",
  "Artifacts",
  "Artifice (WUBR)",
  "Attractions",
  "Auras",
  "Azorius (WU)",
  "Bant (GWU)",
  "Battlecruiser",
  "Birthing Pod / Pod",
  "Blink / Flicker",
  "Blue Moon",
  "Boros (RW)",
  "Budget",
  "Burn",
  "Cascade",
  "Casual",
  "cEDH",
  "Chaos",
  "Chaos (UBRG)",
  "Clones",
  "Coin Flips",
  "Colorless",
  "Combo",
  "Competitive",
  "Control",
  "Cycling",
  "Death & Taxes",
  "Defender",
  "Delver",
  "Devotion",
  "Dimir (UB)",
  "Discard",
  "Discover",
  "Donation",
  "Dredge",
  "Dungeons",
  "Eggs",
  "Enchantments",
  "Energy",
  "Equipment",
  "Esper (WUB)",
  "Extra Combats",
  "Extra Turns",
  "Farm",
  "Five Color (WUBRG)",
  "Flying",
  "Formula X-1",
  "Goad",
  "Golgari (BG)",
  "Goodstuff",
  "Grixis (UBR)",
  "Group Hug",
  "Group Slug",
  "Growth (WUBG)",
  "Gruul (RG)",
  "Hatebears",
  "Help Wanted",
  "Historic",
  "Infect",
  "Izzet (UR)",
  "Jank",
  "Jeskai (URW)",
  "Jund (BRG)",
  "Kindred",
  "Land Destruction",
  "Lands Matter",
  "Legends Matter",
  "Life Bargain",
  "Life Gain",
  "Mardu (RWB)",
  "Maverick",
  "Midrange",
  "Mill",
  "Miracles",
  "Modified",
  "Modular",
  "Monarch",
  "Mono Black",
  "Mono Blue",
  "Mono Green",
  "Mono Red",
  "Mono White",
  "Morph",
  "Mutate",
  "Naya (RGW)",
  "Orzhov (WB)",
  "Pillowfort",
  "PlayEDH - Battlecruiser",
  "PlayEDH - High",
  "PlayEDH - Low",
  "PlayEDH - Maximum",
  "PlayEDH - Mid",
  "Poison",
  "Primer",
  "Prison",
  "Rakdos (BR)",
  "Ramp",
  "Reanimator",
  "Rock",
  "Rule Zero",
  "Selesnya (GW)",
  "Simic (GU)",
  "Snow",
  "Spellslinger",
  "Stax",
  "Stoneblade",
  "Storm",
  "Sultai (BGU)",
  "Super Friends",
  "Tempo",
  "Temur (GUR)",
  "Thieves",
  "Tokens",
  "Toolbox",
  "Tron",
  "Turbo",
  "Unmaintained",
  "Vehicles",
  "Voltron",
  "Vorthos",
  "Webcam Friendly",
  "Wheels",
  "X Spells",
  "Zoo"
];
